sonar.projectKey=Daniax18_Urban-Hub-Project
sonar.organization=daniax18
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=report_tests.xml
sonar.python.flake8.reportPaths=flake8-report.txt

sonar.sourceEncoding=UTF-8
